services:
  _defaults: { autowire: true, autoconfigure: true }
  GeoProxy\: { resource: '../src/' }

  GeoProxy\Service\Routing\StickySessionStoreInterface:
    alias: GeoProxy\Service\Routing\InMemoryStickySessionStore
